# Generated by Django 2.2.2 on 2019-08-04 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gambi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Students'},
        ),
    ]
