# Generated by Django 2.2.2 on 2019-08-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190804_1632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gambi',
        ),
        migrations.AlterField(
            model_name='team',
            name='qtd_students',
            field=models.IntegerField(null=True),
        ),
    ]
