# Generated by Django 2.2.2 on 2019-08-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190804_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='qtd_students',
            field=models.IntegerField(default=0),
        ),
    ]
