# Generated by Django 2.2.2 on 2019-08-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190804_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Type of Product',
                'verbose_name_plural': 'Types of Product',
            },
        ),
    ]
