# Generated by Django 2.2.2 on 2019-08-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190805_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bill',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
