# Generated by Django 2.2.2 on 2019-08-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='date',
            field=models.DateField(default='2019-09-09'),
            preserve_default=False,
        ),
    ]
