# Generated by Django 2.2.2 on 2019-08-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
