# Generated by Django 2.2.2 on 2019-08-06 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20190806_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='studentt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Student'),
        ),
    ]
