# Generated by Django 2.2.2 on 2019-08-06 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_purchase_studentt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='studentt',
            new_name='student',
        ),
    ]
