# Generated by Django 2.2.2 on 2019-08-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20190806_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_1',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_2',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
