# Generated by Django 2.2.2 on 2019-08-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20190806_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeprod',
            name='qtd_prod',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
    ]
